const String javascript PROGMEM = "const headingText = document.querySelector('#heading-value');"
"const arrow = document.querySelector('#arrow');"
"const tbl = document.querySelector('#tbl');"
"console.log('start');"
"const update = () => {"
" console.log('res');"
" console.log('here');"
/*
"  fetch('/data')"
"    .then(res => console.log(res))"
"    .then(res => res.json())"
"    .then(json => { console.log('then', json)"
"      headingText.textContent = `${(json.hdg * 30)}° (${json.hdg})`;"
"      arrow.style.transform = `rotate(${(json.hdg * 30) - 90}deg)`;"
""
"      const keys = Object.keys(json);"
""
"      tbl.innerHTML = '';"
"      console.log(keys);"
""
"      keys.forEach(key => {"
"        if(key === 'hdg') {"
"          return;"
"        }"
"        const row = document.createElement('tr');"
"        const td1 = document.createElement('td');"
"        const td2 = document.createElement('td');"
""
"        td1.textContent = key.charAt(0).toUpperCase() + key.slice(1);"
"        td2.textContent = json[key];"
""
"        row.appendChild(td1);"
"        row.appendChild(td2);"
""
"        tbl.appendChild(row);"
"      });"
"  })"
*/
"}"
"update();";
/*
"window.addEventListener('DOMContentLoaded', () => {"
" console.log('loaded')"
//"  const t = setInterval(update, 1000);"
"});";
*/