const String page PROGMEM = "<!DOCTYPE html><head>"
  " <meta name='viewport' content='width=device-width, initial-scale=1.0'>"
  " <script src='http://www.mackaos.com/clients/ibib/gps/compass.js'></script>"
  " <link rel='stylesheet' href='http://www.mackaos.com/clients/ibib/gps/styles.css'>"
  "</head>"
  "<body>"
  "<div class='container'>"
  "  <h3>ESP32 Magnetometer</h3>"
  "  <div>Uses a NodeMCU-32S and QMC5883L Magnetometer</div>"
  "  <div class='loading'><h3>Loading...</h3></div>"
  "  <div class='wrapper hidden'>"
  "    <h2>Heading: <span id='heading-value'>0</span></h2>"
  "    <div class='compass'>"
  "      <img id='arrow' src='https://i.imgur.com/5buESn2.png'/>"
  "    </div>"
  "    <table id='tbl'></table>"
  "  </div>"
  "</div>"
  "</body>";